### ISSUE TITLE
Getting warning testing `Redirect`

### ISSUE THREAD

**Issue by DanielGibbsNZ** [pshrmn/react-router-test-context#5]
I have the following test suite:

```javascript
import React, {Component} from "react";
import createRouterContext from "react-router-test-context";
import {mount} from "enzyme";
import {PropTypes} from "prop-types";
import {Redirect, Route, Switch} from "react-router-dom";

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {permission: false};
  }

  render() {
    return (
      <Switch>
        <Route exact path="/users">
          <h2>A list of users</h2>
        </Route>
        <Route path="/users/:userId">
          {({match}) => this.state.permission ? <h1>{match.params.userId}</h1> : <Redirect to="/users" />}
        </Route>
      </Switch>
    );
  }
}

describe("render()", () => {
  describe("when route is /users/:userId", () => {
    let app;
    beforeEach(() => {
      const context = createRouterContext({
        location: {pathname: "/users/1"},
        match: {url: "/users/1", path: "/users/:userId", params: {userId: "1"}, isExact: true},
      });
      const childContextTypes = {router: PropTypes.object};
      app = mount(<App />, {context, childContextTypes});
    });

    describe("when user has permission", () => {
      beforeEach(() => {
        app.setState({permission: true});
      });

      it("should show users id", () => {
        expect(app.exists("h1")).toBe(true);
      });
    });

    describe("when user doesn't have permission", () => {
      beforeEach(() => {
        app.setState({permission: false});
      });

      it("should redirect to users list", () => {
        expect(app.exists("Redirect")).toBe(true);
      });
    });
  });
});
```

Both tests pass, but in the second test case I get the following warning:

```
Warning: You tried to redirect to the same route you're currently on: "/users"
```

How should I rewrite my test in order to prevent the warning from occurring?

**Comment by pshrmn** [comment]
That warning occurs when you redirect (using `<Redirect>` or `history.redirect()`) and the app continues to render the same component that triggered the redirect. React Router catches this for you so that you don't get stuck in an infinite redirect loop and displays the warning so you know about it.

I'm not sure exactly why you're getting that error because your `/users` routes doesn't render a redirect. You might try rendering your `<App>` inside of a `<MemoryRouter>` with `react-dom`, instead of using this package and Enzyme, and seeing if the issue persists. That is the more recommended approach to testing React Router applications.

**Comment by DanielGibbsNZ** [comment]
@pshrmn I was hoping to use this package as I felt it made it easier to write easier to understand tests but I've managed to get the tests working using `MemoryRouter` as you suggest so I'll just go with that.
